name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-venv -y
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install Django==5.1.2

      - name: Run migrations and tests
        run: |
          . venv/bin/activate
          python3 manage.py makemigrations
          python3 manage.py migrate
          # Add any additional testing commands if needed

      - name: Build Docker image
        run: |
          docker build -t vijayarajult2/django-todo:${{ github.run_number }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag vijayarajult2/django-todo:${{ github.run_number }} vijayarajult2/django-todo:latest
          docker push vijayarajult2/django-todo:${{ github.run_number }}
          docker push vijayarajult2/django-todo:latest

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d $HOME
          export PATH="$PATH:$HOME/sonar-scanner-4.6.2.2472-linux/bin"

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=django-todo \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Update Helm values
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "vijayarajuyj1@gmail.com"
          git config user.name "vijayrajuyj1"
          sed -i 's/tag: .*/tag: '"${{ github.run_number }}"'/g' helm/demo/values.yaml
          git add helm/demo/values.yaml
          git commit -m "Update deployment image to version ${{ github.run_number }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/vijayrajuyj1/django-project-j HEAD:main
