name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-venv -y
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install Django==5.1.2

      - name: Run migrations and tests
        run: |
          . venv/bin/activate
          python3 manage.py makemigrations
          python3 manage.py migrate
          # Add any additional testing commands if needed

      - name: Build Docker image
        run: |
          docker build -t vijayarajult2/django-todo:${{ github.run_number }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag vijayarajult2/django-todo:${{ github.run_number }} vijayarajult2/django-todo:latest
          docker push vijayarajult2/django-todo:${{ github.run_number }}
          docker push vijayarajult2/django-todo:latest

  

      - name: Update Helm values
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.email "vijayarajuyj1@gmail.com"
          git config user.name "vijayrajuyj1"
          sed -i 's/tag: .*/tag: '"${{ github.run_number }}"'/g' helm/demo/values.yaml
          git add helm/demo/values.yaml
          git commit -m "Update deployment image to version ${{ github.run_number }}"
          git push https://${{ secrets.TOKEN }}@github.com/vijayrajuyj1/django-project-ga HEAD:main
